manifest:
  remotes:
#    - name: zmkfirmware
#      url-base: https://github.com/zmkfirmware
    - name: JoseCondeManuel
      url-base: https://github.com/josecondemanuel
  projects:
    - name: zephyr
      remote: zmk-config
      revision: master
      import: true
  self:
    path: config
